packages:
  - apps/*
  - packages/*
  - workers/*

allowBuilds:
  '@embedded-postgres/darwin-arm64': true
  '@embedded-postgres/darwin-x64': true
  '@embedded-postgres/linux-x64': true
  '@embedded-postgres/windows-x64': true
  '@sentry-internal/node-cpu-profiler': false
  core-js: false
  electron: true
  electron-winstaller: false
  esbuild: true
