/** Semua teks UI web (CLAUDE.md: satu file copy per app). */
export const copy = {
  lead: {
    title: "Satu langkah lagi",
    fields: {
      name: { label: "Nama", placeholder: "Nama lengkap", type: "text", auto: "name" },
      whatsapp: {
        label: "Nomor WhatsApp",
        placeholder: "0812 3456 7890",
        type: "tel",
        auto: "tel",
      },
      email: { label: "Email", placeholder: "nama@email.com", type: "email", auto: "email" },
    },
    submit: "Lihat Fotoku",
    sending: "Mengirim…",
    skip: "Lewati",
    invalid: "Periksa lagi isian dan centang persetujuan",
    failed: "Gagal mengirim, coba lagi",
  },
  publicGallery: {
    link: "Lihat galeri acara",
    title: "Galeri acara",
    back: "‹ Foto kamu",
    gone: "Galeri acara tidak tersedia",
    goneBody: "Penyelenggara belum membuka galeri ini, atau masa simpannya sudah berakhir.",
  },
  guest: {
    strip: "Strip",
    original: "Original",
    animation: "Animasi",
    saveGif: "Simpan GIF ke HP",
    video: "Video",
    saveVideo: "Simpan Video ke HP",
    saveStrip: "Simpan ke Galeri HP",
    saveAll: "Simpan Semua Original",
    saving: "Menyimpan…",
    saveOne: "Simpan foto ini",
    viewerClose: "Tutup",
    viewerPrev: "Foto sebelumnya",
    viewerNext: "Foto berikutnya",
    photoOf: (n: number, m: number) => `Foto ${n} dari ${m}`,
    zoomHint: "Ketuk dua kali untuk zoom",
    availableUntil: "Tersedia sampai",
    poweredBy: "Powered by Tetra Photobooth",
    pendingTitle: "Fotomu lagi dikirim dari booth",
    pendingBody: "Halaman ini akan otomatis muncul begitu fotonya sampai, gak perlu refresh",
    unknownTitle: "Foto kamu belum sampai",
    unknownBody:
      "Biasanya beberapa menit setelah booth tersambung internet. Halaman ini akan muncul otomatis.",
    stepTaken: "Foto diambil",
    stepTakenAt: (t: string) => `${t} · di booth`,
    stepSending: "Mengirim dari booth",
    stepSendingPartial: (n: number, total: number) => `${n} dari ${total} file sudah sampai`,
    stepWaiting: "Menunggu koneksi booth",
    stepWaitingBody: "Booth sedang offline",
    stepHere: "Muncul di sini",
    stepHereBody: "Otomatis",
    keepLink: "Simpan link ini, bisa dibuka lagi nanti",
    goneTitle: "Foto ini sudah tidak tersedia",
    expiredBody: (d: string) => `Masa simpan foto sesi ini sudah berakhir pada ${d}`,
    removedBody: "Foto ini sudah dihapus oleh penyelenggara acara",
    ctaTitle: "Mau photobooth di acaramu?",
    cta: "Hubungi Tetra Photobooth",
  },
  admin: {
    loginTitle: "Masuk ke Admin",
    email: "Email",
    password: "Kata sandi",
    signIn: "Masuk",
    signingIn: "Masuk…",
    noAccess: "Akun ini bukan anggota organisasi",
    signOut: "Keluar",
    loginCards: [
      {
        t: "Booth online",
        d: "Status kamera, printer & kertas tiap menit",
        bg: "bg-mint-soft",
        ml: "ml-0",
      },
      {
        t: "Foto sampai ke tamu",
        d: "Halaman tamu & galeri klien otomatis",
        bg: "bg-lavender",
        ml: "ml-12",
      },
      {
        t: "Satu admin untuk semua event",
        d: "Template, device, dan link klien",
        bg: "bg-butter",
        ml: "ml-4",
      },
    ],
    /** Timer jalannya event (#149). */
    run: {
      title: "Jalannya event",
      state: { idle: "Belum mulai", running: "Berjalan", paused: "Dijeda", finished: "Selesai" },
      start: "Mulai event",
      resume: "Lanjutkan",
      reopen: "Buka lagi",
      pause: "Jeda",
      finish: "Selesai",
      confirm: "Event sudah selesai?",
      confirmYes: "Ya, selesai",
      cancel: "Batal",
      edit: "Ubah jam",
      save: "Simpan jam",
      optional: "opsional",
      started: "Mulai",
      ended: "Selesai",
      paused: "Total jeda",
      package: "Paket",
      noPackage: "Belum diisi",
      left: (d: string) => `sisa ${d}`,
      over: (d: string) => `lewat ${d}`,
      needStart: "Isi jam mulai dulu.",
      hint: "Timer mulai sendiri saat crew menekan Buka untuk Tamu di booth, atau tekan Mulai event.",
      editHint:
        "Untuk membetulkan timer yang lupa ditekan. Jam selesai diisi = event ditandai selesai. Jeda di tengah tetap.",
    },
    /** Kartu rekap event (#148). */
    recap: {
      open: "Rekap event",
      title: "Rekap event",
      copyText: "Salin teks",
      copied: "Teks tersalin",
      download: "Unduh gambar",
      close: "Tutup",
      start: "Mulai",
      end: "Selesai",
      running: "berjalan",
      paused: "Jeda",
      generated: "Dibuat",
      brand: "Tetra Booth",
    },
    nav: {
      events: "Event",
      templates: "Template",
      devices: "Device",
      transactions: "Transaksi",
      team: "Tim",
    },
    forgot: "Lupa kata sandi?",
    forgotTitle: "Atur ulang kata sandi",
    forgotBody: "Masukkan email akunmu. Link untuk membuat kata sandi baru dikirim ke email itu.",
    forgotSend: "Kirim Link",
    forgotSent: "Kalau email ini terdaftar, link atur ulang sudah dikirim. Cek juga folder spam.",
    backToLogin: "Kembali ke halaman masuk",
    passwordTitle: "Buat kata sandi",
    passwordNew: "Kata sandi baru",
    passwordRepeat: "Ulangi kata sandi",
    passwordSave: "Simpan & Masuk",
    passwordShort: "Minimal 8 karakter",
    passwordMismatch: "Kata sandi tidak sama",
    passwordFailed: "Gagal menyimpan kata sandi, coba lagi",
    passwordLinkBad: "Link sudah tidak berlaku atau sudah dipakai. Minta link baru.",
    team: {
      title: "Tim",
      invite: "Undang Anggota",
      inviteTitle: "Undang Anggota",
      send: "Kirim Undangan",
      sending: "Mengirim…",
      close: "Tutup",
      cols: ["Nama", "Email", "Role", "Aktif"],
      roleCards: [
        { v: "admin", t: "Admin", d: "Kelola event" },
        { v: "crew", t: "Crew", d: "Akses terbatas" },
      ],
      sent: (e: string) => `Undangan terkirim ke ${e}. Link di email berlaku 24 jam.`,
      added: (e: string) =>
        `${e} sudah punya akun dan sekarang jadi anggota. Masuk dengan kata sandinya sendiri.`,
      linkNote: (e: string) =>
        `Email ke ${e} tidak bisa dikirim otomatis. Salin link ini dan kirim lewat WhatsApp (berlaku 24 jam):`,
      copy: "Salin Link",
      copied: "Tersalin",
      badEmail: "Email tidak valid",
      already: "Email ini sudah anggota tim. Ubah role-nya dari tabel.",
      failed: "Gagal mengundang, coba lagi",
      never: "Belum masuk",
      inactive: "Nonaktif",
      you: "(kamu)",
      makeRole: (r: string) => `Jadikan ${r}`,
      deactivate: "Nonaktifkan",
      activate: "Aktifkan lagi",
      confirmDeactivate: (e: string) =>
        `Nonaktifkan ${e}? Dia tidak bisa masuk admin sampai diaktifkan lagi.`,
      matrixTitle: "Hak akses per role",
      matrixCols: ["Fitur", "Owner", "Admin", "Crew"],
      matrix: [
        ["Event", "Penuh", "Penuh", "Lihat"],
        ["Template", "Penuh", "Penuh", "Lihat"],
        ["Device", "Penuh", "Penuh", "Lihat"],
        ["Transaksi", "Penuh", "Lihat", "Tidak"],
        ["Tim & Billing", "Penuh", "Tidak", "Tidak"],
        ["Moderasi", "Penuh", "Penuh", "Tidak"],
      ],
    },
    roles: { owner: "Owner", admin: "Admin", crew: "Crew" } as Record<string, string>,
    /** Menyambungkan laptop booth ke akun (desain E5, alur bertahap). Hindari kata "pairing" di layar. */
    devices: {
      add: "Tambah booth",
      addTitle: "Tambah booth",
      repairTitle: (n: string) => `Sambungkan ulang ${n}`,
      repairWhy:
        "Pakai ini kalau laptop booth diganti, Windows/aplikasi diinstal ulang, atau booth menampilkan “Belum tersambung”. Data booth (nama, kode, riwayat) tetap sama.",
      close: "Tutup",
      step1: "Beri nama booth",
      step1Existing: "Booth yang disambungkan",
      step1Hint: "Nama yang mudah dikenali crew, mis. nama pemegang atau lokasinya.",
      namePlaceholder: "mis. Booth Iqbal",
      makeCode: "Buat kode",
      making: "Membuat kode…",
      step2: "Kode untuk laptop booth",
      copyCode: "Salin kode",
      copied: "Tersalin",
      validFor: (mmss: string) => `Berlaku ${mmss}`,
      expired: "Kode sudah kedaluwarsa. Buat kode baru, lalu ketik kode baru di booth.",
      newCode: "Buat kode baru",
      step3: "Ketik kode di laptop booth",
      boothSteps: [
        "Buka aplikasi Tetra Booth di laptop booth.",
        "Masuk Mode Crew: tahan logo 2 detik (atau tekan Ctrl+Shift+M), lalu ketik PIN crew.",
        "Di Ringkasan, langkah 1 “Sambungkan ke akun Tetra”, tekan Sambungkan.",
        "Ketik 6 angka kode di atas, lalu tekan OK.",
      ],
      step4: "Tunggu booth tersambung",
      waiting: "Menunggu laptop booth memakai kode… Halaman ini mendeteksi otomatis.",
      connected: (n: string) => `${n} tersambung`,
      nextTitle: "Langkah berikutnya",
      next: [
        "Di admin: buka Event → pilih event → bagian “Tampil di booth”, centang booth ini (atau Semua booth).",
        "Di laptop booth: tekan Lanjut: Pilih Event, lalu Ambil event terbaru.",
      ],
      toEvents: "Buka daftar event",
      done: "Selesai",
      connect: "Sambungkan",
      reconnect: "Sambungkan ulang",
      deactivate: "Nonaktifkan",
      deactivateTitle: (n: string) => `Nonaktifkan ${n}?`,
      deactivateBody: [
        "Booth ini langsung berhenti mengirim foto dan status ke akun ini, dan hilang dari daftar Device.",
        "Foto dan sesi yang sudah terunggah tetap aman.",
        "Untuk memakai laptop itu lagi, tambah booth baru lalu sambungkan dengan kode baru.",
      ],
      deactivateYes: "Ya, nonaktifkan",
      cancel: "Batal",
      notConnected: "Belum tersambung",
      emptyTitle: "Belum ada booth",
      emptyBody:
        "Sambungkan laptop booth ke akun ini supaya foto terunggah dan kondisinya terpantau di sini.",
      emptySteps: [
        [
          "Tambah booth",
          "Tekan “Tambah booth”, beri nama. Muncul kode 6 angka (berlaku 10 menit).",
        ],
        [
          "Ketik kode di laptop booth",
          "Mode Crew → Ringkasan → Sambungkan ke akun Tetra → ketik kode → OK.",
        ],
        ["Pilih event", "Booth muncul di sini. Atur event mana yang tampil di booth itu."],
      ] as const,
    },
  },
  crash: "Ada yang error. Coba muat ulang halaman.",
} as const;
