/** Semua teks UI booth, Bahasa Indonesia. 08-DESIGN §7: pendek, label tombol maksimal 2 kata. */
export const copy = {
  /** Cetak tamu Guest Cam di printer booth (#223). */
  guestPrint: {
    who: (n: number, name: string | null) => `#${n}${name ? ` ${name}` : ""}`,
    printing: (who: string) => `Cetak Guest Cam ${who}`,
  },
  /** Layar Print Station (#224): laptop + printer khusus cetak foto tamu Guest Cam. */
  printStation: {
    title: "Cetak foto Guest Cam-mu di sini",
    steps: [
      "Scan QR, isi nama, foto pakai HP",
      "Buka Photo frame, pilih fotomu",
      "Tekan Cetak di booth",
      "Ambil cetakanmu di sini",
    ],
    ready: "Siap diambil",
    empty: "Belum ada cetakan. Yang dicetak muncul di sini.",
    failed: "Gagal, panggil crew",
    off: "Add-on cetak Guest Cam belum aktif untuk event ini. Nyalakan di admin → Pengaturan → Guest Cam.",
    noLink: "Link Guest Cam belum dibuat di admin",
    scan: "Scan untuk ikut Guest Cam",
  },
  attract: {
    cta: "Sentuh untuk Mulai",
    // Hanya tampil sebelum PIN crew dibuat (setup pertama), supaya tamu tidak melihatnya saat event.
    crewHint:
      "Booth belum disiapkan. Nanti Mode Crew dibuka dengan menahan logo 2 detik, ketuk pojok kanan atas 5×, atau Ctrl+Shift+M.",
    setup: "Siapkan Booth",
    gallery: "Lihat foto",
    galleryCount: (n: number) => `${n} foto`,
    openPiece: "Buka foto ini",
  },
  /** Galeri tamu dari layar awal, mode event (#145). */
  gallery: {
    title: (event: string) => `Foto ${event}`,
    count: (n: number) => `${n} foto`,
    sub: "Ketuk fotomu untuk scan lagi atau cetak lagi.",
    home: "Kembali ke awal",
    all: "Semua foto",
    latest: "Terbaru",
    hour: (h: string) => `Jam ${h}`,
    loading: "Memuat foto…",
    more: "Memuat foto sebelumnya…",
    empty: "Belum ada foto di acara ini",
    emptyBody: "Foto muncul di sini setelah sesi pertama selesai.",
    prev: "Foto sebelumnya",
    next: "Foto berikutnya",
    session: (t: string) => `Sesi jam ${t}`,
    printed: (n: number) => (n ? `Sudah dicetak ${n} lembar` : "Belum dicetak"),
    scan: "Scan QR",
    scanBody: "Simpan foto ke HP",
    reprint: "Cetak lagi",
    reprintBody: (n: number) => `Masih bisa ${n} lembar`,
    scanTitle: "Scan pakai HP",
    scanSub: "Strip dan foto original ada di sini",
    reprintTitle: "Cetak berapa lagi?",
    reprintGo: (n: number) => `Cetak ${n} lembar`,
    limit: "Batas cetak ulang tercapai, minta bantuan crew",
    back: "Kembali",
  },
  /** Kalimat bawaan di sela foto (#103); yang terakhir = foto terakhir. Bisa diganti per event di admin. */
  prompts: {
    // Sama persis dengan ucapan di sounds/foto-*.wav dan keren-1..4.wav (urutan penting).
    before: [
      "Siap-siap, gaya pertama!",
      "Gaya kedua, lebih seru!",
      "Siap, lebih heboh ya!",
      "Oke gaya terakhir, cheers!",
    ],
    after: ["Mantap!", "Keren banget!", "Cakep!", "Wih, kalcer abis!"],
  },
  countdown: {
    ready: "Siap? Senyum!",
    lookAtCamera: "Lihat ke kamera",
    preparing: "Menyiapkan kamera…",
    waiting: "Sebentar, menunggu foto dari kamera…",
    progress: (n: number, total: number) => `Foto ${n} dari ${total}`,
    snap: "Cekrek!",
  },
  review: {
    title: "Cek fotonya dulu",
    retake: "Ulangi",
    blurry: "Sepertinya kurang tajam",
    next: "Pakai Semua Foto",
    rule: (n: number) => `Tiap foto bisa diulang ${n} kali`,
    retaken: (used: number, max: number) => `Sudah diulang (${used}/${max})`,
  },
  compose: { busy: "Menyusun fotomu…" },
  print: {
    title: "Mau cetak berapa?",
    mode: "Mode Event",
    free: (max: number) => `Gratis, maksimal ${max} lembar`,
    print: "Cetak Sekarang",
    skip: "Tidak Cetak",
    skipped: "Tidak dicetak",
    skippedBody: "Fotomu tetap bisa diunduh lewat QR",
    less: "Kurangi",
    more: "Tambah",
    busy: "Sedang mencetak…",
    done: "Sudah tercetak",
    take: (sheets: number) => `${sheets} lembar · ambil di printer`,
    eta: (sheets: number, sec: number) => `${sheets} lembar · keluar dalam ±${sec} detik`,
    delayed: "Cetakan tertunda sebentar",
    delayedBody: "Printer sedang dicek crew. Fotomu sudah tersimpan dan tetap akan dicetak.",
    queue: "Antrean cetak",
    status: "Status",
    sheets: (n: number) => `${n} lembar`,
    waitCrew: "Menunggu crew",
    scanWhile: "Sambil menunggu, scan dulu",
    digital: "Versi digital langsung ada di HP-mu",
  },
  filter: { title: "Pilih filter", next: "Pakai Filter Ini", back: "Cek Foto Lagi" },
  qr: {
    brand: (b: string) => `Jangan lupa tag ${b}`,
    title: "Scan untuk simpan fotomu",
    sub: "Strip dan foto original ada di sini",
    chips: ["Strip", "Original"],
    offline: "Foto akan tersedia setelah terkirim — QR tetap bisa di-scan sekarang",
    done: "Selesai",
    back: "Kembali ke awal dalam",
    sec: "detik",
  },
  camera: {
    preparing: "Sebentar ya, kamera sedang disiapkan ulang",
    retrying: "Mencoba menghubungkan kembali…",
    attempt: (n: number) => `(percobaan ${n})`,
    safe: "Foto yang sudah diambil tetap aman",
    help: "Butuh bantuan? Panggil crew",
    afTitle: "Crew: kamera tidak mau memotret? Cek di kamera, lalu coba lagi:",
    afSteps: [
      "Putar dial mode ke M (manual)",
      "Matikan live view di kamera (tombol LV, layar belakang kamera mati)",
      "Geser saklar fokus lensa dari AF ke MF, putar ring fokus sampai tajam",
    ],
  },
  payment: {
    expired: "Waktu pembayaran habis",
    expiredBody: "QR sudah tidak berlaku. Buat QR baru untuk lanjut.",
    retry: "Buat ulang",
    tryAgain: "Coba lagi",
    offline: "Pembayaran belum bisa diproses, hubungi crew",
    creating: "Membuat QR…",
    brand: "Tetra Photobooth",
    validFor: "QR berlaku",
    included: "Termasuk",
    oneSheet: "1 lembar cetak",
    extraLine: (n: number, price: string) => `+${n} lembar × ${price}`,
    total: "Total",
    steps: [
      "Buka aplikasi e-wallet atau m-banking",
      "Scan QR",
      "Bayar, layar akan lanjut otomatis",
    ],
    waiting: "Menunggu pembayaran…",
    cancel: "Batalkan",
    cancelSure: "Ya, Batalkan",
    cancelWarn: "Sudah scan atau sudah bayar? Jangan batalkan, tunggu layar lanjut sendiri.",
    paidHelp: "Sudah bayar tapi layar belum lanjut? Panggil crew, uangmu aman.",
    success: "Pembayaran berhasil",
    startsIn: "Sesi foto dimulai dalam",
  },
  design: {
    chooseTitle: "Pilih desain",
    start: "Mulai Foto",
  },
  photobox: {
    steps: ["Layout", "Bayar", "Foto", "Cetak"],
    chooseTitle: "Pilih layout",
    photos: (n: number) => `${n} foto`,
    back: "Kembali",
    toPayment: "Lanjut ke Pembayaran",
    pickHint: "Sentuh desain yang kamu suka",
    pickedHint: "Pilihan bagus! Sentuh tombol di bawah untuk lanjut",
    timeLeft: "Sisa waktu",
    mode: "Mode Photobox",
    includedLine: "1 lembar termasuk paket",
    extraTotal: "Tambahan",
    printOne: "Cetak 1 Saja",
    printPaid: "Cetak Sekarang",
    payPrint: "Bayar & Cetak",
  },
  start: {
    title: "Pilih mode booth",
    admin: "Dashboard Admin",
    edit: "Edit",
    editHint:
      "Edit membuka pengaturan event di admin (browser). Setelah disimpan, tekan Ambil event terbaru.",
    missingHint:
      "Event tidak muncul? Di admin buka event → Pengaturan → Device, pilih Semua booth atau centang booth ini → Simpan, lalu tekan Ambil event terbaru.",
    sub: "Tentukan mode dulu, lalu pilih event.",
    /** Urutan persiapan crew dari layar ini sampai tamu bisa mulai. */
    steps: ["Pilih mode", "Pilih event", "Cek kamera & printer", "Buka untuk tamu"],
    mode: { event: "Mode Event", photobox: "Mode Photobox" },
    modeWhen: {
      event: "Pakai ini kalau booth disewa untuk satu acara (nikahan, ulang tahun, acara kantor).",
      photobox: "Pakai ini kalau booth berdiri di tempat umum (mall, kafe) dan tamu bayar sendiri.",
    },
    modeNext: {
      event: "Cetak gratis, desain dari klien.",
      photobox: "Tamu pilih desain lalu bayar QRIS per sesi. Butuh internet.",
    },
    designs: (n: number) => `${n} desain pilihan`,
    layouts: (n: number) => `${n} layout dijual`,
    count: (n: number) => `${n} event`,
    back: "Ganti mode",
    pickEvent: "pilih event",
    empty:
      "Belum ada event untuk mode ini. Buat event di admin dengan panduan Buat Event, pilih Tampil di booth: Semua booth, lalu tekan Ambil event terbaru.",
    emptyCrew: "Tombol Ambil event terbaru ada di Mode Crew (kanan atas).",
    crew: "Mode Crew",
    backToCrew: "Kembali ke Mode Crew",
  },
  /** Photo Stage (#178): layar operator laptop stage. Tampilan final menyusul dari Claude Design. */
  stage: {
    group: (n: number) => `Rombongan #${n}`,
    // Wizard persiapan A1 (#188).
    setup: {
      crewMode: "Mode Crew",
      steps: ["Peran & event", "Kamera", "TV", "Warna", "Pemisah"],
      titles: [
        ["Laptop ini untuk apa?", "Pilih peran dan event hari ini"],
        ["Kamera", "Sambungkan kamera fotografer, lalu jepret 1 foto tes"],
        ["TV di jalur turun", "Pilih layar tujuan dan coba tampilkan"],
        ["Warna", "Atur dari foto tes, berlaku untuk semua foto"],
        ["Pemisah rombongan", "Kapan rombongan baru dimulai"],
      ],
      roleTitle: "Peran laptop ini",
      roles: [
        ["Booth", "Photobooth biasa: tamu memotret sendiri di layar sentuh."],
        ["Stage", "Fotografer memotret rombongan di pelaminan. QR per rombongan tampil di TV."],
      ],
      roleNote:
        "Laptop booth dan laptop stage memakai event yang sama. Semua foto masuk satu album.",
      changeViaCrew: "Ganti peran, event, atau kamera lewat Crew → Perangkat.",
      eventTitle: "Event",
      today: "Dipakai",
      canon: ["Canon · otomatis", "Kabel USB ke laptop. Tersambung sendiri lewat EDSDK."],
      folder: [
        "Folder pantau",
        "Sony, Lumix, Fujifilm, Nikon. Aplikasi tether pabrikan (Imaging Edge, Lumix Tether, X Acquire, NX Tether, Capture One) atau WiFi kamera menyimpan ke folder ini.",
      ],
      connected: "Tersambung",
      watched: "Dipantau",
      notConnected: "Belum tersambung",
      otherBrand: "Merek lain",
      testTitle: "Jepret 1 foto tes",
      testBody: "Tekan rana di kamera fotografer. Foto muncul di sini dalam beberapa detik.",
      testIn: "Foto tes masuk",
      shootFromLaptop: "Jepret dari laptop",
      laptopScreen: "Layar laptop",
      operator: "Operator",
      tvScreen: "Layar kedua (TV)",
      tvMissing: "Belum terdeteksi",
      tvTest: "Tampilkan uji di TV",
      tvTestOff: "Matikan uji",
      tvTestOn: "Layar uji tampil di TV. Cek dari jalur turun: QR harus terbaca HP dari 2 m.",
      tvHowTitle: "TV harus muncul sebagai layar kedua",
      tvHowBody: "Windows: Win + P → Perluas (Extend).",
      tvHow: [
        ["HDMI nirkabel", "Disarankan untuk pelaminan. Tanpa kabel di lantai, tanpa WiFi."],
        ["HDMI biasa", "Paling stabil. Rapikan kabel."],
        ["Miracast", "Win + K. Bisa patah-patah."],
      ],
      useForAll: "Pakai untuk semua foto",
      autoTitle: "Otomatis setelah jeda",
      autoBody:
        "Kalau kamera diam selama waktu ini, foto berikutnya masuk rombongan baru. Enter tetap bisa dipakai kapan saja.",
      autoRange: "15–180 dtk · bawaan 45",
      offTitle: "Mati",
      offBody:
        "Rombongan baru hanya lewat tombol ⏎. Cocok kalau fotografer sering diam lama di satu rombongan.",
      ready: "Siap mulai",
      sum: ["Peran", "Event", "Kamera", "TV", "Warna", "Pemisah", "Daftar grup"],
      sumTestOk: "foto tes ✓",
      sumTv: (on: boolean) => (on ? "layar kedua tersambung" : "belum tersambung"),
      sumAuto: (s: number | null) => (s === null ? "Mati, hanya tombol" : `Otomatis ${s} dtk`),
      sumGroups: (n: number) => (n ? `${n} grup dari admin` : "Belum ada, nama diketik saat acara"),
      cancel: "Batal",
      back: "Kembali",
      next: ["Lanjut ke Kamera", "Lanjut ke TV", "Lanjut ke Warna", "", "Mulai Photo Stage"],
      hintNoTest: "Bisa lanjut tanpa foto tes, tapi tidak disarankan",
      hintColor: 'Tekan "Pakai untuk semua foto" untuk lanjut',
      lanTitle: "Layar di device lain (tanpa kabel)",
      lanBody: "Laptop/tablet/HP di WiFi atau hotspot yang sama buka alamat ini di browser:",
      lanNone: "Sambungkan laptop ke WiFi/hotspot dulu supaya alamatnya muncul.",
      lanFirewall: "Kalau Windows bertanya, izinkan Tetra Booth di jaringan Private.",
      tvTestScreen: "Uji tampilan TV",
      tvTestScreenSub:
        "Kalau tulisan ini terbaca dari jalur turun dan QR terbaca HP dari 2 m, TV siap.",
    },
    print: "Cetak 4R",
    printing: "Mencetak…",
    printSent: "Dicetak ✓",
    printSentN: (n: number) => `Dicetak ${n}× ✓`,
    printFailed: "Gagal · ulangi",
    // Layar operator final (#186, docs/design/photo-stage).
    camera: "Kamera",
    cameraLost: "Kamera terputus",
    tv: "TV",
    upload: "Upload",
    queued: (n: number) => `${n} antre`,
    internet: "Internet",
    offline: "Offline",
    bannerCamera: [
      "Kamera terputus. Menyambung ulang…",
      "Foto yang sudah masuk tetap aman. Cek kabel USB atau aplikasi tether.",
    ],
    bannerPaused: ["Dijeda.", 'Foto yang masuk ditampung di "Belum dikelompokkan".'],
    bannerTv: [
      "TV tidak tersambung.",
      "Tamu tetap bisa scan QR di layar ini. TV tampil lagi otomatis saat tersambung.",
    ],
    bannerOffline: (n: number) => [
      "Offline.",
      `${n} rombongan antre, terkirim otomatis saat online. Foto tersimpan di laptop.`,
    ],
    press: "Tekan",
    toResume: "untuk lanjut",
    groupCaps: "ROMBONGAN",
    nameLabel: "Nama grup",
    fillHint: "isi dari daftar",
    latest: "terbaru",
    slotTitle: "Foto berikutnya",
    slotSub: "masuk otomatis dari kamera",
    slotCameraSub: "Foto berikutnya masuk setelah tersambung",
    slotPaused: "Dijeda",
    slotPausedSub: 'Foto baru masuk ke "Belum dikelompokkan"',
    emptyTitle: "Menunggu jepretan fotografer",
    emptySub: "Foto masuk otomatis, langsung berwarna preset acara",
    emptyCameraSub: "Menyambung ulang otomatis. Foto yang sudah ada tetap aman.",
    emptyPausedSub: "Tekan Spasi untuk lanjut",
    looseTitle: "Belum dikelompokkan",
    looseSub: (n: number) => `${n} foto masuk saat jeda`,
    looseToActive: (n: number) => `Masukkan ke #${n}`,
    looseToNew: "Jadi rombongan baru",
    looseHide: "Sembunyikan",
    looseHidden: "Foto disembunyikan. Masih ada di folder lokal.",
    lastShot: (s: number) => `jepretan terakhir ${s} dtk lalu`,
    noShot: "belum ada jepretan",
    autoIn: (s: number) => `dipisah otomatis dalam ${s} dtk`,
    autoAfter: (s: number) => `dipisah otomatis ${s} dtk setelah jepretan terakhir`,
    autoOffText: "Pisah otomatis mati · rombongan baru lewat tombol",
    autoPausedText: "Pisah otomatis berhenti saat jeda",
    qrTitle: (n: number) => `QR rombongan #${n}`,
    qrNote: "Untuk tamu yang minta langsung ke crew",
    qrNoteNoTv: "TV mati: arahkan tamu scan di sini",
    nextTitle: "Berikutnya dari daftar",
    nextHint: (n: number) => `Klik = pasang ke #${n}, atau buka rombongan baru`,
    histUploaded: "terunggah",
    histUploading: "mengunggah",
    histQueued: "antre",
    histSaving: "menyimpan",
    histFailed: "gagal simpan",
    histHint: "Klik rombongan untuk ganti nama, gabung, pisah, atau sembunyikan foto",
    histPick: "Pilih foto",
    histPicked: (n: number) => `${n} dipilih`,
    histHidden: "tersembunyi",
    histCount: (shown: number, hidden: number) =>
      hidden ? `${shown} foto · ${hidden} disembunyikan` : `${shown} foto`,
    merge: "Gabung",
    mergeInto: (no: string) => `Gabung ke #${no}`,
    split: "Pisah",
    splitN: (n: number) => `Pisah ${n} foto`,
    hidePhotos: "Sembunyikan",
    showPhotos: "Tampilkan lagi",
    toastMerged: (a: string, b: string) => `#${a} digabung ke #${b}`,
    toastSplit: (n: number, no: string) => `${n} foto jadi rombongan #${no}. Beri nama di atas.`,
    toastHidden: (n: number) => `${n} foto disembunyikan dari tamu & galeri`,
    toastShown: "Foto tampil lagi di halaman tamu & galeri",
    toastPickSplit: "Pilih foto yang mau dipisah dulu",
    toastPickHide: "Pilih foto yang mau disembunyikan dulu",
    toastKeepOne: "Sisakan minimal 1 foto di rombongan ini",
    toastWaitSave: "Tunggu rombongan selesai disimpan dulu",
    toastTooMany: "Maksimal 20 foto per rombongan",
    autoOn: "Aktif",
    lan: (url: string) => `Layar WiFi ${url}`,
    // HP helper crew (#206).
    helper: {
      button: "HP crew",
      title: "Ganti nama rombongan dari HP",
      body: "Crew kedua di WiFi/hotspot yang sama scan QR ini. Nama yang diketik di HP langsung masuk ke laptop.",
      none: "Sambungkan laptop ke WiFi/hotspot dulu supaya HP crew bisa tersambung.",
      code: (k: string) => `Kode ${k}`,
      close: "Tutup",
      pageTitle: "Nama rombongan",
      active: "Rombongan terbaru",
      next: "Pasang dari daftar",
      earlier: "Rombongan sebelumnya",
      save: "Simpan",
      saved: "Tersimpan",
      wrongKey: 'Kode salah. Scan ulang QR "HP crew" dari laptop.',
      offline: "Laptop tidak terjangkau. Pastikan HP di WiFi/hotspot yang sama.",
      empty: "Belum ada rombongan. Nama dari daftar bisa langsung dipasang.",
    },
    shoot: "Jepret",
    shooting: "Menjepret…",
    toastOpened: (n: number, prev: number) => `Rombongan #${n} dibuka. QR #${prev} tampil di TV`,
    toastEmpty: (n: number) => `Rombongan #${n} masih kosong`,
    toastAutoClosed: (sec: number, n: number) => `Jeda ${sec} dtk lewat. Rombongan #${n} ditutup`,
    namePlaceholder: "Nama grup (boleh kosong)",
    waiting: "Menunggu jepretan fotografer…",
    waitingHint: "Foto masuk otomatis dari kamera. Tekan Enter kalau rombongan berikutnya naik.",
    newGroup: "Rombongan baru",
    pause: "Jeda",
    resume: "Lanjut",
    paused: "Dijeda: jepretan ditampung, belum masuk rombongan",
    loose: (n: number) => `${n} foto belum dikelompokkan`,
    assignLoose: "Masukkan ke rombongan",
    auto: "Pisah otomatis",
    autoOff: "Mati",
    sec: (n: number) => `${n} dtk`,
    history: "Riwayat",
    photos: (n: number) => `${n} foto`,
    saving: "menyimpan…",
    saved: "tersimpan",
    failed: "gagal disimpan, dicoba lagi",
    color: "Warna",
    colorTitle: "Warna foto stage",
    colorHint: "Diatur dari foto tes. Berlaku untuk semua foto berikutnya.",
    before: "Sebelum",
    after: "Sesudah",
    compareHint: "Geser garis untuk membandingkan",
    testShot: (time: string, model: string | null) =>
      `foto tes · ${time}${model ? ` · ${model}` : ""}`,
    lutNoneLabel: "Belum ada file",
    lutNote: "LUT dipakai dulu, lalu filter dan slider.",
    lutBroken: "File LUT tidak bisa dibaca. Pastikan formatnya .cube 3D (LUT_3D_SIZE).",
    presetLabel: "Preset",
    presetAuto: "Tersimpan otomatis untuk event ini",
    lut: "LUT (.cube)",
    lutPick: "Pilih file .cube",
    lutNone: "Tanpa LUT. Filter & slider dipakai setelah LUT.",
    lutRemove: "Hapus",
    lutTooBig: "File terlalu besar. Maksimal 8 MB (LUT 65 titik atau lebih kecil).",
    brightness: "Kecerahan",
    contrast: "Kontras",
    saturation: "Saturasi",
    warmth: "Kehangatan",
    reset: "Kembalikan",
    done: "Selesai",
    noPhoto: "Jepret satu foto tes dulu untuk melihat hasilnya.",
    crew: "Crew",
    keys: "⏎ rombongan baru · Spasi jeda/lanjut",
    next: "Berikutnya:",
    doneCount: (done: number, all: number) => `${done}/${all} grup sudah`,
    tvOn: "TV tersambung",
    tvOff: "TV tidak tersambung",
    tvScan: "Scan untuk ambil fotomu",
    tvIdleQr: "Belum dapat\nfotomu?",
    tvIdleQrSub: "Cari di sini",
    tvGroupAt: (no: string, time: string) => `Rombongan #${no} · ${time}`,
    tvFind: "Cari fotomu",
    tvFindSub: "Ketuk rombonganmu untuk melihat foto & QR-nya",
    tvClose: "Tutup",
    tvAll: "Semua rombongan",
    tvNone: "Belum ada rombongan yang difoto",
    tvPrev: "Rombongan sebelumnya",
    tvIdle: "Foto dari pelaminan akan tampil di sini",
  },
  crew: {
    nav: {
      home: "Ringkasan",
      camera: "Kamera",
      printer: "Printer",
      event: "Event & Desain",
      system: "Sistem",
    },
    toGuest: "Buka untuk Tamu",
    camera: "Kamera",
    cameraService: "Layanan kamera",
    connected: "Terhubung",
    down: "Mati",
    changeEvent: "Ganti Event",
    systemTitle: "Tampilan & startup",
    openCameraCheck: "Live View & Tes Jepret",
    cameraSettingsTitle: "Setelan kamera (langsung)",
    designTitle: "Desain frame & layar awal",
    designAdmin: "Buka di admin",
    mainDesign: "Desain utama",
    editDesign: "Edit desain",
    designLocal: (at: string) => `Diubah di booth · ${at}`,
    designCloud: "Sama dengan cloud",
    designSaved: "Tersimpan di booth ini · dipakai sesi berikutnya",
    designLoading: "Membuka desain…",
    designReset: (name: string) => `${name} dikembalikan ke versi cloud`,
    presetsAdminOnly: "Tata letak saya hanya bisa disimpan dari admin",
    designNote:
      "Edit di booth = hanya booth ini, tanpa internet, langsung dipakai sesi berikutnya. Untuk mengubah desain di cloud (semua booth), buka di admin lalu tekan Ambil event terbaru.",
    cloudTitle: "Cloud & perangkat",
    appTitle: "Aplikasi",
    title: "Mode Crew",
    exit: "Tutup Aplikasi",
    exitConfirm: "Tutup aplikasi booth?",
    exitBody:
      "Booth berhenti sampai aplikasi dibuka lagi. Cetakan yang sedang antre tetap diselesaikan dulu.",
    exitYes: "Ya, Tutup Aplikasi",
    update: "Update Aplikasi",
    updateChecking: "Mengecek versi terbaru…",
    updateLatest: (v: string) => `Sudah versi terbaru (${v}).`,
    updateNone: "Belum ada rilis di cloud.",
    updateOffline: "Tidak bisa cek update. Pastikan booth sudah dipasangkan dan internet menyala.",
    updateReady: (latest: string, current: string) =>
      `Versi ${latest} sudah diunduh (terpasang ${current}). Pemasangan ±1 menit: booth tertutup lalu terbuka lagi sendiri.`,
    updateAvailable: (latest: string, current: string) =>
      `Versi ${latest} tersedia (terpasang ${current}). Booth mengunduh ±150 MB, lalu tertutup dan terbuka lagi sendiri dalam ±1 menit. Jangan matikan laptop.`,
    updateNow: "Pasang Sekarang",
    cursorShown: "Kursor: tampil",
    cursorHidden: "Kursor: sembunyi",
    updateInstalling: "Unduhan selesai. Memasang… booth tertutup lalu terbuka lagi sendiri.",
    updateFailed: "Update gagal",
    updateRetry: "Coba Lagi",
    updateDone: (v: string) => `Update berhasil: Tetra Booth ${v}`,
    updateNotInstalled: (to: string, now: string) =>
      `Update ke ${to} gagal dipasang, booth masih versi ${now}. Coba lagi dari Mode Crew → Update Aplikasi.`,
    adminOpened: "Dashboard admin dibuka di browser. Klik Tetra Booth di taskbar untuk kembali.",
    updating: "Mengunduh update… booth akan tertutup lalu terbuka lagi",
    updateProgress: (mb: number, total: number, pct: number, eta: string) =>
      `Mengunduh update ${mb} / ${total} MB (${pct}%)${eta} · booth tertutup lalu terbuka lagi setelah selesai`,
    activeEvent: "Event aktif",
    back: "Kembali",
    pinEnter: "Masukkan PIN crew",
    pinCreate: "Buat PIN crew (4–6 digit)",
    pinConfirm: "Ulangi PIN",
    pinWrong: "PIN salah",
    pinMismatch: "PIN tidak sama, ulangi",
    pinLocked: (s: number) => `Terlalu banyak salah. Coba lagi ${s} detik`,
    ok: "OK",
    del: "Hapus",
    cancel: "Batal",
    online: "Online",
    offline: "Offline",
    defaultEvent: "Event default",
    ready: "Siap",
    printerTitle: "Printer",
    printerState: (s: string) =>
      s === "ready" ? "Siap" : s === "unknown" ? "Belum terdeteksi" : "Bermasalah",
    connection: "Koneksi",
    retryUpload: "Kirim ulang sekarang",
    sharpen: {
      title: "Tajamkan foto lama",
      body: "Foto strip sesi lama di galeri & halaman tamu masih resolusi rendah. Booth merender ulang strip web 2× dari foto asli di laptop ini lalu mengunggahnya lagi. Sesi yang desain atau filternya tidak bisa dipastikan sama dilewati. Tetap di Mode Crew sampai selesai.",
      start: "Mulai tajamkan",
      progress: (done: number, total: number, skipped: number) =>
        `${done} / ${total} sesi · ${skipped} dilewati`,
      summary: (x: {
        total: number;
        done: number;
        updated: number;
        mismatch: number;
        skipped: number;
      }) =>
        x.total === 0
          ? "Tidak ada sesi lama yang perlu ditajamkan."
          : `${x.done < x.total ? `Dibatalkan di ${x.done} / ${x.total} sesi` : "Selesai"}: ${x.updated} diperbarui · ${x.mismatch} tidak cocok (desain berubah) · ${x.skipped} dilewati (foto atau event tidak ada di booth). Foto diperbarui terkirim lewat antrean upload.`,
    },
    unsent: (n: number) => `${n} file belum terkirim`,
    allSent: "Semua foto sudah terkirim",
    cursor: "Kursor mouse di layar tamu",
    cursorOn: "Tampil",
    cursorOff: "Sembunyi",
    autoStart: "Buka otomatis saat laptop menyala",
    testShot: "Tes Jepret",
    cameraSettings: "Setelan kamera",
    focus: "Fokus",
    focusAf: "AF",
    focusNear: "dekat",
    focusFar: "jauh",
    focusMeter: "ketajaman live view",
    tapToFocus: "Ketuk subjek di live view untuk fokus",
    groupLive: "Kecerahan monitor",
    groupLiveHint: "Atur sampai tamu terlihat jelas di layar booth.",
    darker: "Lebih gelap",
    brighter: "Lebih terang",
    auto: "Otomatis",
    level: (n: number, of: number) => `Level ${n} dari ${of}`,
    flicker: "Anti kedip lampu",
    flickerHint: "Indonesia 50 Hz. Coba 60 Hz kalau layar bergaris.",
    groupShot: "Saat jepret (foto)",
    groupShotHint: 'Hanya dipakai saat memotret. "Sama dengan live view" = ikut kecerahan monitor.',
    groupOther: "Lainnya",
    autoFocus: "Fokus otomatis",
    sharpnessNow: "Ketajaman live view",
    sharpnessBest: "terbaik",
    lastShot: "Hasil tes terakhir",
    noShot: "Belum ada tes. Tekan Tes Jepret.",
    shotInfo: (w: number, h: number, sec: string) => `${w}×${h} · ${sec} detik`,
    shooting: "Memotret…",
    shotNo: (n: number) => `Tes #${n}`,
    shotHint: "Klik foto untuk memperbesar, membandingkan, dan memakai setelannya.",
    compare: "Bandingkan",
    guides: "Garis bantu",
    older: "Sebelumnya",
    newer: "Sesudahnya",
    close: "Tutup",
    useSettings: "Pakai setelan ini",
    settingsApplied: (n: number, line: string) => `Setelan Tes #${n} dipakai saat jepret: ${line}`,
    focusPeak: "puncak",
    afBeforeCapture: "AF sebelum tiap jepret",
    paper: (r: number, c: number) => `Kertas ${r} / ${c} lembar`,
    paperLow: "Kertas hampir habis",
    newRoll: "Ganti Roll Kertas",
    rollSize: "Isi roll baru (lembar)",
    save: "Simpan",
    testPrint: "Tes Cetak",
    printTone: {
      title: "Warna cetakan (printer ini)",
      note: "Hasil cetak lebih terang atau pudar dari layar? Turunkan kecerahan, naikkan kontras & saturasi, lalu Tes Cetak. Layar dan galeri tidak berubah.",
      brightness: "Kecerahan",
      contrast: "Kontras",
      saturation: "Saturasi",
      reset: "Kembalikan",
    },
    printerSettings: "Setel Printer",
    device: "Kamera & Printer",
    eventSettings: "Pengaturan Event",
    setting: {
      countdownSec: "Hitung mundur (detik)",
      retakeMax: "Jatah foto ulang",
      maxPrints: "Maks. cetak per sesi",
      qrScreenSec: "Layar QR (detik)",
      sessionSec: "Timer sesi photobox (detik)",
    },
    cloudValue: (v: number) => `cloud: ${v}`,
    changedHere: "diubah di booth",
    changedHereBadge: "Pengaturan diubah di booth",
    resetToCloud: "Kembalikan ke cloud",
    eventSettingsNote:
      "Hanya berlaku di booth ini. Ambil event terbaru tidak menimpanya. Template & harga diatur di admin.",
    eventSettingsSaved: "Pengaturan event disimpan di booth",
    eventSettingsReset: "Pengaturan event kembali ke cloud",
    deviceRole: "Peran laptop",
    roles: { booth: "Photobooth", stage: "Photo Stage", print: "Print Station" },
    /** Hapus isinya (jadikan "") setelah W-038…W-041 lulus dengan kamera Sony asli (#171). */
    sonyUntested: "Belum diuji dengan kamera asli" as string,
    sonyTips: [
      "Menu kamera: USB Connection = PC Remote (A7 IV ke atas: PC Remote Function = On, sambungan USB).",
      "Still Img. Save Dest. = PC Only, format file JPEG (RAW+J PC Save Img = JPEG Only), ukuran L.",
      "Putar dial ke M. Power Save Start Time 30 menit, USB Power Supply On atau baterai dummy.",
      "Kabel USB langsung ke laptop, bukan hub. Tutup Imaging Edge sebelum booth dibuka.",
      "Tap to focus hanya A7 IV ke atas (Focus Area: Spot / Expand Flexible Spot).",
    ],
    /** Hapus isinya (jadikan "") setelah W-043 lulus dengan GH5 Rama (#214). */
    lumixUntested: "Belum diuji dengan kamera asli" as string,
    lumixTips: [
      "Menu kamera: Setup → USB Mode = PC(Tether). Tutup aplikasi LUMIX Tether sebelum booth dibuka.",
      "Kualitas JPEG Fine (bukan RAW). Foto dikirim ke laptop, kartu memori tidak wajib.",
      "Putar dial ke M. Setup → Economy → Sleep Mode OFF. Event panjang: baterai dummy + adaptor AC.",
      "Kabel USB-C langsung ke laptop, bukan hub. Tap to focus tidak ada; pakai tombol AF atau AF sebelum jepret.",
    ],
    /** Hapus isinya (jadikan "") setelah W-044 lulus dengan kamera Nikon asli (#216). */
    nikonUntested: "Belum diuji dengan kamera asli" as string,
    nikonTips: [
      "Sambungkan lewat USB langsung ke laptop. Tutup NX Tether, Camera Control Pro, dan Nikon Transfer sebelum booth dibuka.",
      "Kualitas JPEG (bukan RAW). Foto dikirim ke laptop, kartu memori tidak wajib.",
      "Putar dial ke M. Perpanjang timer mati otomatis; event panjang pakai baterai dummy + adaptor AC.",
      "Z6III, Zf, Z30, Zfc, Z5II, Z50II, ZR butuh Windows 11. D3200–D3500 belum didukung SDK Nikon.",
      "Tap to focus belum ada; pakai tombol AF atau AF sebelum jepret.",
    ],
    /** Alur kerja crew di Ringkasan (perombakan UI crew, Okt 2026): siapkan → selama acara → setelah acara. */
    flow: {
      title: "Alur kerja crew",
      steps: ["Siapkan booth", "Selama acara", "Setelah acara"] as const,
      state: { done: "Selesai", now: "Sekarang", next: "Nanti" },
      localEvent:
        "Pantau kamera, kertas, dan upload di sini. Event lokal tanpa timer acara: rekap dihitung dari sesi.",
      open: "Buka",
      paper: "Kertas",
      paperHint: "Dihitung dari cetakan booth ini. Isi ulang setiap ganti roll.",
      failedTodo: "Cek di halaman Printer, lalu cetak ulang",
      upload: "Upload ke halaman tamu",
      account: "Akun Tetra",
      afterHint:
        "Setelah Hentikan Acara, rekap muncul sendiri: jumlah sesi & cetak, link galeri klien, dan folder foto untuk diserahkan.",
      noPrinterPicked: "Printer belum dipilih",
      eventHint: "Pilih event dulu di Pilih Event.",
      cursorHint: "Tampilkan kalau layar tamu dipakai dengan mouse.",
      autoStartHint: "Booth langsung terbuka saat laptop dinyalakan.",
      updateHint: "Cek versi terbaru. Pasang hanya di luar jam acara.",
      checkUpdate: "Cek Update",
      pin: "PIN crew",
      pinHint: "PIN untuk masuk ke mode crew.",
      exitHint: "Booth berhenti sampai aplikasi dibuka lagi.",
      navHint: "Layar tamu tampil. Masuk lagi: ketuk pojok kanan atas 5×.",
    },
    paperShort: (n: number) => `Kertas ±${n}`,
    cameraHelp: "Cek kabel USB & kamera menyala. Kamera salah? Ganti di Kamera yang dipakai.",
    cameraSettingsHint: "Langsung dikirim ke kamera. Lihat efeknya di Tes Jepret.",
    cameraSettingsNone: "Setelan dari booth hanya untuk kamera Canon, Nikon, Sony, dan Lumix.",
    /** Halaman Kamera/Printer/Sistem setelah perombakan UI crew (Okt 2026): pilihan perangkat di halamannya. */
    dev: {
      cameraTitle: "Kamera yang dipakai",
      cameraHint: "Pilih merek kamera yang tercolok ke laptop, lalu Simpan & Mulai Ulang.",
      locked: "Dikunci teknisi: diatur dari pengaturan aplikasi, tidak bisa diubah di sini.",
      choice: {
        canon: { title: "Canon", detail: "DSLR & mirrorless EOS lewat USB" },
        nikon: { title: "Nikon", detail: "D-series & Z lewat USB" },
        sony: { title: "Sony", detail: "A7 II/III/IV/V, A7C, A6100–A6700" },
        lumix: { title: "Lumix", detail: "GH5 lewat USB" },
        webcam: { title: "Webcam", detail: "Kamera USB atau bawaan laptop" },
        simulated: { title: "Latihan tanpa kamera", detail: "Foto contoh, untuk belajar alur" },
        hotfolder: { title: "Hot folder", detail: "Diatur teknisi" },
      },
      untestedTag: "Belum diuji",
      howTo: (brand: string) => `Cara setel kamera ${brand}`,
      open: "Buka",
      close: "Tutup",
      webcamTitle: "Webcam yang dipakai",
      viewTitle: "Cermin & fokus",
      mirror: {
        mirrorLiveView: {
          label: "Cermin di layar tamu",
          hint: "Tamu melihat dirinya seperti di cermin. Biasanya nyala.",
        },
        mirrorPhoto: {
          label: "Cermin di hasil foto",
          hint: "Tulisan di baju & latar ikut terbalik di cetakan. Biasanya mati.",
        },
      },
      afHint: "Kamera fokus ulang di awal tiap hitung mundur.",
      printerTitle: "Printer yang dipakai",
      printerHint: "Printer yang sudah terpasang di Windows.",
      cutTitle: "Potong 2 inci",
      roleHint: "Pilih sekali saat setup. Ganti peran = booth dibuka ulang.",
      roleDetail: {
        booth: "Tamu berfoto sendiri di booth ini",
        stage: "Foto dari kamera fotografer di pelaminan",
        print: "Hanya mencetak foto tamu Guest Cam (tanpa photobooth)",
      },
      saveTitle: "Perubahan perangkat belum disimpan",
      saveHint: "Booth ditutup lalu terbuka lagi sendiri (±10 detik).",
      changed: {
        camera: "Kamera",
        webcamId: "Webcam",
        hotFolder: "Folder hot folder",
        hotFolderTrigger: "Pemicu shutter",
        mirrorLiveView: "Cermin di layar tamu",
        mirrorPhoto: "Cermin di hasil foto",
        afBeforeCapture: "AF sebelum jepret",
        printer: "Printer",
        role: "Peran laptop",
      },
      canonTips: [
        "Sambungkan kamera lewat USB langsung ke laptop, bukan hub.",
        "Putar dial ke M, kualitas JPEG. Matikan auto power off atau pakai baterai dummy.",
        "File pendukung Canon diunduh otomatis saat booth online.",
      ],
    },
    noWebcam: "Tidak ada webcam terdeteksi.",
    on: "Nyala",
    off: "Mati",
    noPrinter: "Tidak ada printer terdeteksi. Pasang driver printer di Windows dulu.",
    hotFolder: "Folder hot folder",
    hotFolderTrigger: "Alamat pemicu shutter",
    noExposure:
      "Setelan ISO dan shutter tampil setelah kamera tersambung. Bisa juga diatur langsung di kamera.",
    cutOn:
      "Event ini mencetak strip 2R. Di Setel Printer, nyalakan potong 2 inci (2inch cut: Enable).",
    cutOff:
      "Event ini mencetak 4R/polaroid. Di Setel Printer, matikan potong 2 inci (2inch cut: Disable).",
    deviceSave: "Simpan & Mulai Ulang",
    sharpBase: (n: number) => `patokan ketajaman ${n}`,
    blurWarn:
      "Foto di 2 dari 3 sesi terakhir sepertinya kurang tajam. Cek fokus kamera, lalu Tes Jepret untuk patokan baru.",
    blurFix: "Cek Kamera",
    blurDismiss: "Tutup",
    deviceRestarting: "Menyimpan… booth ditutup lalu terbuka lagi",
    printerSettingsDone:
      "Dialog printer ditutup. 2inch cut: Enable untuk strip 2R, Disable untuk 4R & polaroid.",
    sent: "Dikirim ke printer, menunggu hasil…",
    printed: "Tercetak",
    printFailed: (m: string) => `Gagal cetak: ${m}`,
    failedPrints: "Cetak gagal",
    none: "Belum ada",
    reprint: "Cetak ulang",
    uncertain:
      "Mungkin sudah tercetak. Cek lembar yang keluar dulu, cetak ulang hanya kalau tidak ada.",
    changePin: "Ganti PIN",
    autoStartDev: "Auto-start hanya di app hasil build",
    /** Menyambungkan booth ke akun Tetra (crew tidak perlu tahu istilah "pairing"). */
    pairTitle: "Sambungkan ke akun Tetra",
    pairPurpose:
      "Supaya foto terunggah ke halaman tamu, event dari admin bisa diunduh, dan kondisi booth terpantau. Sesi foto tetap jalan tanpa ini.",
    pairStepsTitle: "Cara dapat kodenya",
    pairSteps: (host: string) => [
      `Minta admin membuka ${host}/admin → Device → Tambah booth.`,
      "Admin mengetik nama booth, lalu layarnya menampilkan kode 6 angka. Kode berlaku 10 menit.",
      "Ketik 6 angka itu di sini, lalu tekan OK.",
    ],
    pairEnter: "Ketik 6 angka dari admin",
    pairAlreadyTitle: "Booth ini sudah tersambung",
    pairAlready: (name: string, code: string) => `Tersambung sebagai ${name} · ${code}`,
    pairAgainWhy:
      "Sambungkan ulang hanya kalau admin memberi kode baru untuk laptop ini: laptop diganti, aplikasi diinstal ulang, atau pindah ke akun Tetra lain.",
    pairBack: "Kembali ke Menu Crew",
    pairAgain: "Sambungkan Ulang",
    pairing: "Menyambungkan…",
    pairDoneTitle: "Tersambung",
    pairDone: (name: string, code: string) =>
      `Booth ini sekarang tersambung sebagai ${name} · ${code}.`,
    pairDoneHint: "Berikutnya: pilih event yang akan dipakai, lalu cek kamera dan printer.",
    pairNext: "Lanjut: Pilih Event",
    pair: "Sambungkan ke akun Tetra",
    paired: (name: string, code: string) => `${name} · ${code}`,
    unpaired: "Belum tersambung",
    revoked: "Tidak terhubung: booth dicabut di admin, pasangkan ulang",
    revokedPill: "Dicabut",
    pairNew: "Pasangkan Ulang",
    /** Checklist persiapan di atas menu crew: urutan kerja crew sebelum tamu datang. */
    setup: {
      title: "Siapkan booth",
      sub: "Ikuti urutan ini sebelum tamu datang. Hijau = siap.",
      pair: "Sambungkan ke akun Tetra",
      pairTodo: "Butuh kode 6 angka dari admin",
      optional: "Boleh dilewati",
      ready: "Siap",
      pairAction: "Sambungkan",
      event: "Pilih event",
      eventTodo: "Belum ada event dipilih",
      eventAction: "Pilih Event",
      eventChange: "Ganti",
      camera: "Cek kamera",
      cameraOk: "Kamera tersambung",
      cameraTodo: "Kamera belum tersambung",
      cameraAction: "Tes Jepret",
      pickCamera: "Pilih Kamera",
      version: "Cek versi aplikasi",
      versionChecking: "Mengecek versi terbaru…",
      versionLatest: (v: string) => `Versi ${v}, sudah terbaru`,
      versionNew: (latest: string, current: string) =>
        `Versi ${latest} tersedia (booth masih ${current}). Pasang ±1 menit, sebaiknya sebelum tamu datang.`,
      versionOffline: (v: string) =>
        `Versi ${v}. Tidak bisa dicek sekarang (offline atau belum tersambung).`,
      versionSkipped: (latest: string, current: string) =>
        `Dilewati. Booth tetap ${current}; versi ${latest} bisa dipasang nanti dari sini atau Sistem.`,
      versionUpdate: "Update",
      versionSkip: "Lewati",
      versionRetry: "Cek Lagi",
      versionNav: "Update tersedia",
      pickPrinter: "Pilih Printer",
      printer: "Cek printer",
      printerOk: "Printer siap",
      printerTodo: "Printer belum siap",
      printerAction: "Tes Cetak",
      open: "Buka untuk Tamu",
      openHint: "Layar tamu tampil. Masuk lagi ke sini: ketuk pojok kanan atas 5×.",
      more: "Lainnya",
    },
    /** Timer event (#149, #152): data untuk rekap, tidak membatasi booth. */
    run: {
      title: "Jalannya acara",
      state: {
        idle: "Belum mulai",
        waiting: "Menunggu sesi pertama",
        running: "Berjalan",
        paused: "Dijeda",
        finished: "Selesai",
      },
      idle: "Tekan Buka untuk Tamu, lalu pilih Mulai acara.",
      waiting: "Timer mulai sendiri saat tamu pertama berfoto.",
      running: "Jeda kalau acara berhenti sebentar (makan, sambutan). Hentikan saat acara selesai.",
      paused: "Timer berhenti. Tekan Lanjutkan Acara saat acara mulai lagi.",
      finished: "Waktu acara sudah dicatat. Lihat rekapnya di sini.",
      pause: "Jeda Acara",
      resume: "Lanjutkan Acara",
      finish: "Hentikan Acara",
      recap: "Rekap Acara",
      confirm: "Acara sudah selesai? Timer berhenti dan rekap muncul.",
      confirmYes: "Ya, Hentikan",
      cancel: "Batal",
      offline: "Tersimpan di laptop, dikirim ke cloud saat online",
      since: (start: string, dur: string) => `Mulai ${start} · sudah berjalan ${dur}`,
    },
    /** Pop-up Buka untuk Tamu (#152): mulai acara sungguhan atau tes dulu. */
    go: {
      title: "Acara sudah mulai?",
      titlePaused: "Acara sedang dijeda",
      sub: "Pilih Mulai acara kalau tamu sudah boleh berfoto. Belum? Tes dulu.",
      subPaused: "Lanjutkan kalau acara sudah jalan lagi. Mau coba kamera dulu? Tes dulu.",
      titleFinished: "Acara sudah dihentikan",
      subFinished:
        "Tamu masih mau berfoto? Lanjutkan acara supaya waktunya ikut tercatat. Mau coba kamera saja? Tes dulu.",
      start: "Mulai acara",
      startNote: "Timer mulai sendiri saat tamu pertama berfoto.",
      resume: "Lanjutkan acara",
      resumeNote: "Timer jalan lagi mulai sekarang.",
      test: "Tes dulu",
      testNote: "Foto tes tidak dihitung dan tidak tampil di galeri.",
      close: "Kembali ke menu crew",
      guide: "Nanti selama acara",
      enter: "Masuk mode crew",
      corner: "Ketuk pojok kanan atas 5×",
      hold: "atau tahan logo 2 detik",
      keys: "atau tekan",
      pin: "lalu ketik PIN crew",
      steps: [
        ["Jeda", "Mode crew → Ringkasan → Jeda Acara"],
        ["Hentikan", "Mode crew → Ringkasan → Hentikan Acara. Rekap muncul sendiri."],
        ["Lihat rekap lagi", "Mode crew → Ringkasan → Rekap Acara"],
      ],
    },
    /** Kartu rekap acara di booth (#154): dari data laptop ini, jalan offline. */
    recap: {
      title: "Rekap acara",
      sessions: "Sesi tamu",
      prints: "Lembar dicetak",
      first: "Sesi pertama",
      last: "Sesi terakhir",
      start: "Mulai",
      end: "Selesai",
      paused: "Jeda",
      running: "berjalan",
      tests: (n: number) => `${n} sesi tes tidak dihitung`,
      outside: (n: number) => `${n} sesi di luar waktu acara`,
      noRun: "Timer belum jalan. Durasi dihitung dari sesi pertama sampai terakhir.",
      okPkg: "Sesuai paket",
      over: (t: string) => `Lebih ${t} dari paket`,
      under: (t: string) => `Kurang ${t} dari paket`,
      ran: (t: string) => `Berjalan ${t}`,
      pkg: (t: string) => `Paket ${t}`,
      planned: "Jadwal",
      actual: "Nyata",
      thisLaptop: "Dihitung dari laptop ini. Rekap lengkap ada di dashboard admin.",
      folder: "Buka Folder Event",
      folderNote: "Salin semua foto ke flashdisk dari folder ini.",
      size: "Ukuran file di laptop",
      sizeValue: (size: string, n: number) => `${size} · ${n.toLocaleString("id-ID")} file`,
      sizeHint: "Pastikan flashdisk punya ruang kosong lebih dari ini.",
      sizeLoading: "Menghitung…",
      drive: (name: string, free: string) => `Flashdisk ${name} kosong ${free}`,
      driveOk: "cukup",
      driveLow: "tidak cukup",
      folderDone: (path: string) => `Folder dibuka: ${path}`,
      link: "Salin Link Galeri",
      linkDone: (url: string) => `Link tersalin: ${url}`,
      close: "Tutup",
    },
    testBadge: "TES",
    testHint: "Mode tes · foto tidak dihitung",
    syncEvents: "Ambil event terbaru",
    syncing: "Mengunduh event dari cloud…",
    synced: (n: number) => (n ? `${n} event diperbarui` : "Event sudah terbaru"),
  },
} as const;
