/** Semua teks UI booth, Bahasa Indonesia. 08-DESIGN §7: pendek, label tombol maksimal 2 kata. */
export const copy = {
  attract: {
    cta: "Sentuh untuk Mulai",
    // Hanya tampil sebelum PIN crew dibuat (setup pertama), supaya tamu tidak melihatnya saat event.
    crewHint:
      "Booth belum disiapkan. Nanti Mode Crew dibuka dengan menahan logo 2 detik, ketuk pojok kanan atas 5×, atau Ctrl+Shift+M.",
    setup: "Siapkan Booth",
    gallery: "Lihat foto",
    galleryCount: (n: number) => `${n} foto`,
    openPiece: "Buka foto ini",
  },
  /** Galeri tamu dari layar awal, mode event (#145). */
  gallery: {
    title: (event: string) => `Foto ${event}`,
    count: (n: number) => `${n} foto`,
    sub: "Ketuk fotomu untuk scan lagi atau cetak lagi.",
    home: "Kembali ke awal",
    all: "Semua foto",
    latest: "Terbaru",
    hour: (h: string) => `Jam ${h}`,
    loading: "Memuat foto…",
    more: "Memuat foto sebelumnya…",
    empty: "Belum ada foto di acara ini",
    emptyBody: "Foto muncul di sini setelah sesi pertama selesai.",
    prev: "Foto sebelumnya",
    next: "Foto berikutnya",
    session: (t: string) => `Sesi jam ${t}`,
    printed: (n: number) => (n ? `Sudah dicetak ${n} lembar` : "Belum dicetak"),
    scan: "Scan QR",
    scanBody: "Simpan foto ke HP",
    reprint: "Cetak lagi",
    reprintBody: (n: number) => `Masih bisa ${n} lembar`,
    scanTitle: "Scan pakai HP",
    scanSub: "Strip dan foto original ada di sini",
    reprintTitle: "Cetak berapa lagi?",
    reprintGo: (n: number) => `Cetak ${n} lembar`,
    limit: "Batas cetak ulang tercapai, minta bantuan crew",
    back: "Kembali",
  },
  /** Kalimat bawaan di sela foto (#103); yang terakhir = foto terakhir. Bisa diganti per event di admin. */
  prompts: {
    // Sama persis dengan ucapan di sounds/foto-*.wav dan keren-1..4.wav (urutan penting).
    before: [
      "Siap-siap, gaya pertama!",
      "Gaya kedua, lebih seru!",
      "Siap, lebih heboh ya!",
      "Oke gaya terakhir, cheers!",
    ],
    after: ["Mantap!", "Keren banget!", "Cakep!", "Wih, kalcer abis!"],
  },
  countdown: {
    ready: "Siap? Senyum!",
    lookAtCamera: "Lihat ke kamera",
    preparing: "Menyiapkan kamera…",
    waiting: "Sebentar, menunggu foto dari kamera…",
    progress: (n: number, total: number) => `Foto ${n} dari ${total}`,
    snap: "Cekrek!",
  },
  review: {
    title: "Cek fotonya dulu",
    retake: "Ulangi",
    blurry: "Sepertinya kurang tajam",
    next: "Pakai Semua Foto",
    rule: (n: number) => `Tiap foto bisa diulang ${n} kali`,
    retaken: (used: number, max: number) => `Sudah diulang (${used}/${max})`,
  },
  compose: { busy: "Menyusun fotomu…" },
  print: {
    title: "Mau cetak berapa?",
    mode: "Mode Event",
    free: (max: number) => `Gratis, maksimal ${max} lembar`,
    print: "Cetak Sekarang",
    skip: "Tidak Cetak",
    skipped: "Tidak dicetak",
    skippedBody: "Fotomu tetap bisa diunduh lewat QR",
    less: "Kurangi",
    more: "Tambah",
    busy: "Sedang mencetak…",
    done: "Sudah tercetak",
    take: (sheets: number) => `${sheets} lembar · ambil di printer`,
    eta: (sheets: number, sec: number) => `${sheets} lembar · keluar dalam ±${sec} detik`,
    delayed: "Cetakan tertunda sebentar",
    delayedBody: "Printer sedang dicek crew. Fotomu sudah tersimpan dan tetap akan dicetak.",
    queue: "Antrean cetak",
    status: "Status",
    sheets: (n: number) => `${n} lembar`,
    waitCrew: "Menunggu crew",
    scanWhile: "Sambil menunggu, scan dulu",
    digital: "Versi digital langsung ada di HP-mu",
  },
  filter: { title: "Pilih filter", next: "Pakai Filter Ini", back: "Cek Foto Lagi" },
  qr: {
    brand: (b: string) => `Jangan lupa tag ${b}`,
    title: "Scan untuk simpan fotomu",
    sub: "Strip dan foto original ada di sini",
    chips: ["Strip", "Original"],
    offline: "Foto akan tersedia setelah terkirim — QR tetap bisa di-scan sekarang",
    done: "Selesai",
    back: "Kembali ke awal dalam",
    sec: "detik",
  },
  camera: {
    preparing: "Sebentar ya, kamera sedang disiapkan ulang",
    retrying: "Mencoba menghubungkan kembali…",
    attempt: (n: number) => `(percobaan ${n})`,
    safe: "Foto yang sudah diambil tetap aman",
    help: "Butuh bantuan? Panggil crew",
  },
  payment: {
    expired: "Waktu pembayaran habis",
    expiredBody: "QR sudah tidak berlaku. Buat QR baru untuk lanjut.",
    retry: "Buat ulang",
    tryAgain: "Coba lagi",
    offline: "Pembayaran belum bisa diproses, hubungi crew",
    creating: "Membuat QR…",
    brand: "Tetra Photobooth",
    validFor: "QR berlaku",
    included: "Termasuk",
    oneSheet: "1 lembar cetak",
    extraLine: (n: number, price: string) => `+${n} lembar × ${price}`,
    total: "Total",
    steps: [
      "Buka aplikasi e-wallet atau m-banking",
      "Scan QR",
      "Bayar, layar akan lanjut otomatis",
    ],
    waiting: "Menunggu pembayaran…",
    cancel: "Batalkan",
    cancelSure: "Ya, Batalkan",
    cancelWarn: "Sudah scan atau sudah bayar? Jangan batalkan, tunggu layar lanjut sendiri.",
    paidHelp: "Sudah bayar tapi layar belum lanjut? Panggil crew, uangmu aman.",
    success: "Pembayaran berhasil",
    startsIn: "Sesi foto dimulai dalam",
  },
  design: {
    chooseTitle: "Pilih desain",
    start: "Mulai Foto",
  },
  photobox: {
    steps: ["Layout", "Bayar", "Foto", "Cetak"],
    chooseTitle: "Pilih layout",
    photos: (n: number) => `${n} foto`,
    back: "Kembali",
    toPayment: "Lanjut ke Pembayaran",
    pickHint: "Sentuh desain yang kamu suka",
    pickedHint: "Pilihan bagus! Sentuh tombol di bawah untuk lanjut",
    timeLeft: "Sisa waktu",
    mode: "Mode Photobox",
    includedLine: "1 lembar termasuk paket",
    extraTotal: "Tambahan",
    printOne: "Cetak 1 Saja",
    printPaid: "Cetak Sekarang",
    payPrint: "Bayar & Cetak",
  },
  start: {
    title: "Pilih mode booth",
    admin: "Dashboard Admin",
    edit: "Edit",
    editHint:
      "Edit membuka pengaturan event di admin (browser). Setelah disimpan, tekan Ambil event terbaru.",
    missingHint:
      "Event tidak muncul? Di admin buka event → Pengaturan → Device, pilih Semua booth atau centang booth ini → Simpan, lalu tekan Ambil event terbaru.",
    sub: "Tentukan mode dulu, lalu pilih event.",
    /** Urutan persiapan crew dari layar ini sampai tamu bisa mulai. */
    steps: ["Pilih mode", "Pilih event", "Cek kamera & printer", "Buka untuk tamu"],
    mode: { event: "Mode Event", photobox: "Mode Photobox" },
    modeWhen: {
      event: "Pakai ini kalau booth disewa untuk satu acara (nikahan, ulang tahun, acara kantor).",
      photobox: "Pakai ini kalau booth berdiri di tempat umum (mall, kafe) dan tamu bayar sendiri.",
    },
    modeNext: {
      event: "Cetak gratis, desain dari klien.",
      photobox: "Tamu pilih desain lalu bayar QRIS per sesi. Butuh internet.",
    },
    designs: (n: number) => `${n} desain pilihan`,
    layouts: (n: number) => `${n} layout dijual`,
    count: (n: number) => `${n} event`,
    back: "Ganti mode",
    pickEvent: "pilih event",
    empty:
      "Belum ada event untuk mode ini. Buat event di admin dengan panduan Buat Event, pilih Tampil di booth: Semua booth, lalu tekan Ambil event terbaru.",
    emptyCrew: "Tombol Ambil event terbaru ada di Mode Crew (kanan atas).",
    crew: "Mode Crew",
    backToCrew: "Kembali ke Mode Crew",
  },
  crew: {
    nav: {
      home: "Ringkasan",
      camera: "Kamera",
      printer: "Printer",
      event: "Event & Desain",
      system: "Sistem",
    },
    toGuest: "Buka untuk Tamu",
    camera: "Kamera",
    cameraService: "Layanan kamera",
    connected: "Terhubung",
    down: "Mati",
    changeEvent: "Ganti Event",
    systemTitle: "Tampilan & startup",
    openCameraCheck: "Live View & Tes Jepret",
    cameraSettingsTitle: "Setelan kamera (langsung)",
    printerSource: "Pilih printer & kamera",
    designTitle: "Desain frame & layar awal",
    designAdmin: "Buka di admin",
    mainDesign: "Desain utama",
    editDesign: "Edit desain",
    designLocal: (at: string) => `Diubah di booth · ${at}`,
    designCloud: "Sama dengan cloud",
    designSaved: "Tersimpan di booth ini · dipakai sesi berikutnya",
    designLoading: "Membuka desain…",
    designReset: (name: string) => `${name} dikembalikan ke versi cloud`,
    presetsAdminOnly: "Tata letak saya hanya bisa disimpan dari admin",
    designNote:
      "Edit di booth = hanya booth ini, tanpa internet, langsung dipakai sesi berikutnya. Untuk mengubah desain di cloud (semua booth), buka di admin lalu tekan Ambil event terbaru.",
    cloudTitle: "Cloud & perangkat",
    appTitle: "Aplikasi",
    title: "Mode Crew",
    exit: "Tutup Aplikasi",
    exitConfirm: "Tutup aplikasi booth?",
    exitBody:
      "Booth berhenti sampai aplikasi dibuka lagi. Cetakan yang sedang antre tetap diselesaikan dulu.",
    exitYes: "Ya, Tutup Aplikasi",
    update: "Update Aplikasi",
    updateChecking: "Mengecek versi terbaru…",
    updateLatest: (v: string) => `Sudah versi terbaru (${v}).`,
    updateNone: "Belum ada rilis di cloud.",
    updateReady: (latest: string, current: string) =>
      `Versi ${latest} sudah diunduh (terpasang ${current}). Pemasangan ±1 menit: booth tertutup lalu terbuka lagi sendiri.`,
    updateAvailable: (latest: string, current: string) =>
      `Versi ${latest} tersedia (terpasang ${current}). Booth mengunduh ±150 MB, lalu tertutup dan terbuka lagi sendiri dalam ±1 menit. Jangan matikan laptop.`,
    updateNow: "Pasang Sekarang",
    cursorShown: "Kursor: tampil",
    cursorHidden: "Kursor: sembunyi",
    updateInstalling: "Unduhan selesai. Memasang… booth tertutup lalu terbuka lagi sendiri.",
    updateFailed: "Update gagal",
    updateRetry: "Coba Lagi",
    updateDone: (v: string) => `Update berhasil: Tetra Booth ${v}`,
    updateNotInstalled: (to: string, now: string) =>
      `Update ke ${to} gagal dipasang, booth masih versi ${now}. Coba lagi dari Mode Crew → Update Aplikasi.`,
    adminOpened: "Dashboard admin dibuka di browser. Klik Tetra Booth di taskbar untuk kembali.",
    updating: "Mengunduh update… booth akan tertutup lalu terbuka lagi",
    updateProgress: (mb: number, total: number, pct: number, eta: string) =>
      `Mengunduh update ${mb} / ${total} MB (${pct}%)${eta} · booth tertutup lalu terbuka lagi setelah selesai`,
    activeEvent: "Event aktif",
    back: "Kembali",
    pinEnter: "Masukkan PIN crew",
    pinCreate: "Buat PIN crew (4–6 digit)",
    pinConfirm: "Ulangi PIN",
    pinWrong: "PIN salah",
    pinMismatch: "PIN tidak sama, ulangi",
    pinLocked: (s: number) => `Terlalu banyak salah. Coba lagi ${s} detik`,
    ok: "OK",
    del: "Hapus",
    cancel: "Batal",
    online: "Online",
    offline: "Offline",
    defaultEvent: "Event default",
    ready: "Siap",
    printerTitle: "Printer",
    printerState: (s: string) =>
      s === "ready" ? "Siap" : s === "unknown" ? "Belum terdeteksi" : "Bermasalah",
    connection: "Koneksi",
    retryUpload: "Kirim ulang sekarang",
    sharpen: {
      title: "Tajamkan foto lama",
      body: "Foto strip sesi lama di galeri & halaman tamu masih resolusi rendah. Booth merender ulang strip web 2× dari foto asli di laptop ini lalu mengunggahnya lagi. Sesi yang desain atau filternya tidak bisa dipastikan sama dilewati. Tetap di Mode Crew sampai selesai.",
      start: "Mulai tajamkan",
      progress: (done: number, total: number, skipped: number) =>
        `${done} / ${total} sesi · ${skipped} dilewati`,
      summary: (x: {
        total: number;
        done: number;
        updated: number;
        mismatch: number;
        skipped: number;
      }) =>
        x.total === 0
          ? "Tidak ada sesi lama yang perlu ditajamkan."
          : `${x.done < x.total ? `Dibatalkan di ${x.done} / ${x.total} sesi` : "Selesai"}: ${x.updated} diperbarui · ${x.mismatch} tidak cocok (desain berubah) · ${x.skipped} dilewati (foto atau event tidak ada di booth). Foto diperbarui terkirim lewat antrean upload.`,
    },
    unsent: (n: number) => `${n} file belum terkirim`,
    allSent: "Semua foto sudah terkirim",
    duringEvent: "Saat event berlangsung",
    more: "Pengaturan lain",
    moreHint: "Kamera & printer, pengaturan event, PIN, update, tutup aplikasi",
    cursor: "Kursor mouse di layar tamu",
    cursorOn: "Tampil",
    cursorOff: "Sembunyi",
    autoStart: "Buka otomatis saat laptop menyala",
    testShot: "Tes Jepret",
    cameraSettings: "Setelan kamera",
    focus: "Fokus",
    focusAf: "AF",
    focusNear: "dekat",
    focusFar: "jauh",
    focusMeter: "ketajaman live view",
    tapToFocus: "Ketuk subjek di live view untuk fokus",
    groupLive: "Kecerahan live view",
    groupLiveHint: "Supaya tamu terlihat jelas di layar.",
    groupShot: "Saat jepret (foto)",
    groupShotHint: 'Hanya dipakai saat memotret. "Sama dengan live view" = ikut setelan di atas.',
    groupOther: "Lainnya",
    autoFocus: "Fokus otomatis",
    focusFine: "Geser fokus",
    sharpnessNow: "Ketajaman live view",
    sharpnessBest: "terbaik",
    lastShot: "Hasil tes terakhir",
    noShot: "Belum ada tes. Tekan Tes Jepret.",
    shotInfo: (w: number, h: number, sec: string) => `${w}×${h} · ${sec} detik`,
    shooting: "Memotret…",
    shotNo: (n: number) => `Tes #${n}`,
    shotHint: "Klik foto untuk memperbesar, membandingkan, dan memakai setelannya.",
    compare: "Bandingkan",
    guides: "Garis bantu",
    older: "Sebelumnya",
    newer: "Sesudahnya",
    close: "Tutup",
    useSettings: "Pakai setelan ini",
    settingsApplied: (n: number, line: string) => `Setelan Tes #${n} dipakai saat jepret: ${line}`,
    focusPeak: "puncak",
    afBeforeCapture: "AF sebelum tiap jepret",
    paper: (r: number, c: number) => `Kertas ${r} / ${c} lembar`,
    paperLow: "Kertas hampir habis",
    newRoll: "Ganti Roll Kertas",
    rollSize: "Isi roll baru (lembar)",
    save: "Simpan",
    testPrint: "Tes Cetak",
    printerSettings: "Setel Printer",
    device: "Kamera & Printer",
    eventSettings: "Pengaturan Event",
    setting: {
      countdownSec: "Hitung mundur (detik)",
      retakeMax: "Jatah foto ulang",
      maxPrints: "Maks. cetak per sesi",
      qrScreenSec: "Layar QR (detik)",
      sessionSec: "Timer sesi photobox (detik)",
    },
    cloudValue: (v: number) => `cloud: ${v}`,
    changedHere: "diubah di booth",
    changedHereBadge: "Pengaturan diubah di booth",
    resetToCloud: "Kembalikan ke cloud",
    eventSettingsNote:
      "Hanya berlaku di booth ini. Ambil event terbaru tidak menimpanya. Template & harga diatur di admin.",
    eventSettingsSaved: "Pengaturan event disimpan di booth",
    eventSettingsReset: "Pengaturan event kembali ke cloud",
    deviceCamera: "Kamera",
    devicePrinter: "Printer",
    deviceLocked: "dikunci teknisi",
    cameraKind: {
      webcam: "Webcam",
      canon: "Kamera DSLR Canon",
      hotfolder: "DSLR lain (digiCamControl)",
      simulated: "Latihan tanpa kamera",
    },
    canonNote:
      "Sambungkan kamera lewat USB, putar ke mode M, kualitas JPEG. File pendukung Canon diunduh otomatis saat booth online.",
    noWebcam: "Tidak ada webcam terdeteksi.",
    on: "Nyala",
    off: "Mati",
    mirror: "Cermin (balik kiri-kanan)",
    mirrorLiveView: "Live view",
    mirrorPhoto: "Hasil foto",
    mirrorNote: "Hasil foto dibalik: tulisan di baju & latar ikut terbalik di cetakan.",
    noPrinter: "Tidak ada printer terdeteksi. Pasang driver printer di Windows dulu.",
    hotFolder: "Folder hot folder",
    hotFolderFromDcc: "Mengikuti folder sesi digiCamControl",
    hotFolderTrigger: "Alamat pemicu shutter",
    noExposure:
      "Setelan ISO dan shutter tampil setelah kamera tersambung. Bisa juga diatur langsung di kamera.",
    cutOn:
      "Event ini mencetak strip 2R. Di Setel Printer, nyalakan potong 2 inci (2inch cut: Enable).",
    cutOff:
      "Event ini mencetak 4R/polaroid. Di Setel Printer, matikan potong 2 inci (2inch cut: Disable).",
    noChange: "Belum ada perubahan untuk disimpan",
    deviceSave: "Simpan & Mulai Ulang",
    sharpBase: (n: number) => `patokan ketajaman ${n}`,
    blurWarn:
      "Foto di 2 dari 3 sesi terakhir sepertinya kurang tajam. Cek fokus kamera, lalu Tes Jepret untuk patokan baru.",
    blurFix: "Kamera & Printer",
    blurDismiss: "Tutup",
    deviceRestarting: "Menyimpan… booth ditutup lalu terbuka lagi",
    printerSettingsDone:
      "Dialog printer ditutup. 2inch cut: Enable untuk strip 2R, Disable untuk 4R & polaroid.",
    sent: "Dikirim ke printer, menunggu hasil…",
    printed: "Tercetak",
    printFailed: (m: string) => `Gagal cetak: ${m}`,
    failedPrints: "Cetak gagal",
    none: "Belum ada",
    reprint: "Cetak ulang",
    uncertain:
      "Mungkin sudah tercetak. Cek lembar yang keluar dulu, cetak ulang hanya kalau tidak ada.",
    changePin: "Ganti PIN",
    autoStartDev: "Auto-start hanya di app hasil build",
    /** Menyambungkan booth ke akun Tetra (crew tidak perlu tahu istilah "pairing"). */
    pairTitle: "Sambungkan ke akun Tetra",
    pairPurpose:
      "Supaya foto terunggah ke halaman tamu, event dari admin bisa diunduh, dan kondisi booth terpantau. Sesi foto tetap jalan tanpa ini.",
    pairStepsTitle: "Cara dapat kodenya",
    pairSteps: (host: string) => [
      `Minta admin membuka ${host}/admin → Device → Tambah booth.`,
      "Admin mengetik nama booth, lalu layarnya menampilkan kode 6 angka. Kode berlaku 10 menit.",
      "Ketik 6 angka itu di sini, lalu tekan OK.",
    ],
    pairEnter: "Ketik 6 angka dari admin",
    pairAlreadyTitle: "Booth ini sudah tersambung",
    pairAlready: (name: string, code: string) => `Tersambung sebagai ${name} · ${code}`,
    pairAgainWhy:
      "Sambungkan ulang hanya kalau admin memberi kode baru untuk laptop ini: laptop diganti, aplikasi diinstal ulang, atau pindah ke akun Tetra lain.",
    pairBack: "Kembali ke Menu Crew",
    pairAgain: "Sambungkan Ulang",
    pairing: "Menyambungkan…",
    pairDoneTitle: "Tersambung",
    pairDone: (name: string, code: string) =>
      `Booth ini sekarang tersambung sebagai ${name} · ${code}.`,
    pairDoneHint: "Berikutnya: pilih event yang akan dipakai, lalu cek kamera dan printer.",
    pairNext: "Lanjut: Pilih Event",
    pair: "Sambungkan ke akun Tetra",
    paired: (name: string, code: string) => `${name} · ${code}`,
    unpaired: "Belum tersambung",
    /** Checklist persiapan di atas menu crew: urutan kerja crew sebelum tamu datang. */
    setup: {
      title: "Siapkan booth",
      sub: "Ikuti urutan ini sebelum tamu datang. Hijau = siap.",
      pair: "Sambungkan ke akun Tetra",
      pairTodo: "Butuh kode 6 angka dari admin",
      optional: "Boleh dilewati",
      ready: "Siap",
      pairAction: "Sambungkan",
      event: "Pilih event",
      eventTodo: "Belum ada event dipilih",
      eventAction: "Pilih Event",
      eventChange: "Ganti",
      camera: "Cek kamera",
      cameraOk: "Kamera tersambung",
      cameraTodo: "Kamera belum tersambung",
      cameraAction: "Tes Jepret",
      pickDevice: "Pilih Perangkat",
      printer: "Cek printer",
      printerOk: "Printer siap",
      printerTodo: "Printer belum siap",
      printerAction: "Tes Cetak",
      open: "Buka untuk Tamu",
      openHint: "Layar tamu tampil. Masuk lagi ke sini: tahan logo 2 detik.",
      more: "Lainnya",
    },
    /** Timer event (#149): data untuk rekap admin, tidak membatasi booth. */
    run: {
      title: "Jalannya event",
      state: { idle: "Belum mulai", running: "Berjalan", paused: "Dijeda", finished: "Selesai" },
      idle: "Timer mulai sendiri saat kamu menekan Buka untuk Tamu.",
      running: "Jeda kalau acara berhenti sebentar (makan, sambutan). Selesai saat acara selesai.",
      paused: "Timer berhenti. Tekan Lanjutkan, atau Buka untuk Tamu, saat acara mulai lagi.",
      finished: "Waktu event sudah dicatat untuk rekap.",
      pause: "Jeda Event",
      resume: "Lanjutkan Event",
      finish: "Selesai Event",
      confirm: "Acara sudah selesai?",
      confirmYes: "Ya, Selesai",
      cancel: "Batal",
      offline: "Tersimpan di laptop, dikirim ke cloud saat online",
    },
    syncEvents: "Ambil event terbaru",
    syncing: "Mengunduh event dari cloud…",
    synced: (n: number) => (n ? `${n} event diperbarui` : "Event sudah terbaru"),
  },
} as const;
